---
title: "make_AlphaMissense_supplementary"
author: "Tram Nguyen"
date: "2024-07-15"
output: html_document
editor_options: 
  markdown: 
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(width = 80)
```

```{r, warning=FALSE}
suppressMessages(library(dplyr))
```

# Download processed data

The original .csv table is available for download through the [AlphaMissense
Supplementary Data](https://www.science.org/doi/suppl/10.1126/science.adg7492/suppl_file/science.adg7492_data_s1_to_s9.zip).

# Load in ProteinGym supplemental table from Cheng et al. 2023
```{r}
# table S8
cheng_suppl <- read.csv("~/Desktop/R/docker-data/AlphaMissense_data/data_s1_to_s9/Supplementary_Data_S8_proteingym.csv")
cheng_suppl <- as.data.frame(cheng_suppl)
```

A data.frame with 87 ProteinGym assays and 4 fields:
"DMS_id", "Uniprot_ID", "variant_id", "AlphaMissense".

# Write ProteinGym DMS list to RDS object
```{r, eval=FALSE}
# Save locally:
MAVE.dir <- "~/Desktop/R/docker-data/AlphaMissense_data/DMS_ProteinGym_substitutions/"

saveRDS(cheng_suppl, paste0(MAVE.dir,"Cheng_ProteinGym_S8_supplementary.RDS"))
```

# SessionInfo
```{r}
sessionInfo()
```

